controller:
  serviceAccount:
    create: false
    name: jenkins-sa
  nodeSelector:
    node-role.kubernetes.io/devops-node: devops-node
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingress: 
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hostName: jenkins.local.k8s.com 
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.local.k8s.com
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
persistence:
  enabled: true
  existingClaim: jenkins-pvc
